-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 13:57:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_bank` DEFAULT CHARACTER SET utf8 ;
USE `bd_bank` ;

-- -----------------------------------------------------
-- Table `bd_bank`.`taccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`taccount` (
  `idaccount` INT(11) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `balance` DECIMAL(22,6) NULL DEFAULT NULL,
  `openDate` DATETIME NULL DEFAULT NULL,
  `idemployee` INT(11) NOT NULL,
  `idagencies` INT(11) NOT NULL,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`taccounttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`taccounttype` (
  `idaccounttype` INT(11) NOT NULL AUTO_INCREMENT,
  `accountType` VARCHAR(45) NULL DEFAULT NULL,
  `comission` DECIMAL(22,6) NULL DEFAULT NULL,
  `overdraft` DECIMAL(22,6) NULL DEFAULT NULL,
  `interestRate` DECIMAL(22,6) NULL DEFAULT NULL,
  PRIMARY KEY (`idaccounttype`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tadmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tadmin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tbank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tbank` (
  `idbank` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `capital` DECIMAL(20,0) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbank`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tdirectoragencie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tdirectoragencie` (
  `idtdirectorAgencie` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `salary` DECIMAL(22,6) NULL DEFAULT NULL,
  PRIMARY KEY (`idtdirectorAgencie`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tagencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tagencies` (
  `idagencies` INT(11) NOT NULL AUTO_INCREMENT,
  `agencyNumber` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `idbank  INT(11) NOT NULL,
  `idtdirectorAgencie` INT(11) NOT NULL,
  PRIMARY KEY (`idagencies`),
  INDEX `fk_tagencies_tbank1_idx` (`idbank` ASC),
  INDEX `fk_tagencies_tdirectorAgencie1_idx` (`idtdirectorAgencie` ASC),
  CONSTRAINT `fk_tagencies_tbank1`
    FOREIGN KEY (`idbank`)
    REFERENCES `bd_bank`.`tbank` (`idbank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagencies_tdirectorAgencie1`
    FOREIGN KEY (`idtdirectorAgencie`)
    REFERENCES `bd_bank`.`tdirectoragencie` (`idtdirectorAgencie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tarea` (
  `codearea` VARCHAR(3) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codearea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`temployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`temployee` (
  `idemployee` INT(11) NOT NULL AUTO_INCREMENT,
  `employeeNumber` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `hiringDate` DATE NULL DEFAULT NULL,
  `idagencies` INT(11) NOT NULL,
  PRIMARY KEY (`idemployee`),
  INDEX `fk_temployee_tagencies1_idx` (`idagencies` ASC),
  CONSTRAINT `fk_temployee_tagencies1`
    FOREIGN KEY (`idagencies`)
    REFERENCES `bd_bank`.`tagencies` (`idagencies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tclient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tclient` (
  `idclient` INT(11) NOT NULL AUTO_INCREMENT,
  `clientNumber` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `cardNumber` VARCHAR(45) NULL DEFAULT NULL,
  `nip` VARCHAR(45) NULL DEFAULT NULL,
  `idagencies` INT(11) NOT NULL,
  `idemployee` INT(11) NOT NULL,
  PRIMARY KEY (`idclient`),
  INDEX `fk_tclient_tagencies1_idx` (`idagencies` ASC),
  INDEX `fk_tclient_temployee1_idx` (`idemployee` ASC),
  CONSTRAINT `fk_tclient_tagencies1`
    FOREIGN KEY (`idagencies`)
    REFERENCES `bd_bank`.`tagencies` (`idagencies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tclient_temployee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `bd_bank`.`temployee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tclient_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tclient_account` (
  `idaccounttype` INT(11) NOT NULL,
  `idclient` INT(11) NOT NULL,
  `idaccount` INT(11) NOT NULL,
  PRIMARY KEY (`idaccounttype`, `idclient`),
  INDEX `fk_tclient_account_tclient1_idx` (`idclient` ASC),
  INDEX `fk_tclient_account_taccount1_idx` (`idaccount` ASC),
  CONSTRAINT `fk_tclient_account_taccount1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bd_bank`.`taccount` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tclient_account_taccounttype1`
    FOREIGN KEY (`idaccounttype`)
    REFERENCES `bd_bank`.`taccounttype` (`idaccounttype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tclient_account_tclient1`
    FOREIGN KEY (`idclient`)
    REFERENCES `bd_bank`.`tclient` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`tdirectorgeneral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`tdirectorgeneral` (
  `iddirector` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `salary` DECIMAL(22,6) NULL DEFAULT NULL,
  `idbank` INT(11) NOT NULL,
  PRIMARY KEY (`iddirector`, `idbank`),
  INDEX `fk_tdirector_tbank1_idx` (`idbank` ASC),
  CONSTRAINT `fk_tdirector_tbank1`
    FOREIGN KEY (`idbank`)
    REFERENCES `bd_bank`.`tbank` (`idbank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`temploy_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`temploy_area` (
  `idemployee` INT(11) NOT NULL,
  `codearea` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idemployee`, `codearea`),
  INDEX `fk_temploy_area_area1_idx` (`codearea` ASC),
  CONSTRAINT `fk_temploy_area_area1`
    FOREIGN KEY (`codearea`)
    REFERENCES `bd_bank`.`tarea` (`codearea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temploy_area_temployee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `bd_bank`.`temployee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_bank`.`ttransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bank`.`ttransaction` (
  `idtransaction` INT(11) NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(22,6) NULL DEFAULT NULL,
  `transactionDate` DATETIME NULL DEFAULT NULL,
  `comission` DECIMAL(22,6) NULL DEFAULT NULL,
  `overdraft` DECIMAL(22,6) NULL DEFAULT NULL,
  `interestRate` DECIMAL(22,6) NULL DEFAULT NULL,
  `idaccount` INT(11) NOT NULL,
  `idclient` INT(11) NOT NULL,
  `idemployee` INT(11) NOT NULL,
  `idagencies` INT(11) NOT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `fk_ttransaction_taccount1_idx` (`idaccount` ASC, `idclient` ASC, `idemployee` ASC, `idagencies` ASC),
  CONSTRAINT `fk_ttransaction_taccount1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bd_bank`.`taccount` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bd_bank` ;

-- -----------------------------------------------------
-- procedure sp_save_accounts
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_accounts`(
/*taccount*/
in aidaccount int(11),
in anumber varchar(45),
in abalance DECIMAL(22,6),
in aidclient int(11),
in aidemployee int(11),
in aidagencies int(11),
/*taccounttype*/
in aidaccounttype int(11),
in aaccountType varchar(45),
in acomission DECIMAL(22,6),
in aoverdraft DECIMAL(22,6),
in ainterestRate DECIMAL(22,6),
/*ttransaction*/
in aidtransaction int(11)
-- in aidclient int(11),
-- in aidemployee int(11),
-- in aidagencies int(11)
)
BEGIN
/*	Ajouter les inserts des tables taccount, tauteur, tclassement, tediteur  etc */ 
/*taccount*/
IF  aidaccount = 0  THEN
	INSERT INTO `bd_bank`.`taccount`(`idaccount`,`number`,`balance`,`idclient`,`idemployee`,`idagencies`)
	                          VALUES(aidaccount,anumber,abalance,aidclient,aidemployee,aidagencies);
	SELECT 
    MAX(idaccount)
INTO aidaccount FROM
    bd_bank.taccount;
ELSE
   UPDATE `bd_bank`.`taccount`
   SET `number` = `anumber`,`balance` = `abalance`,`idclient` = `aidclient`,`idemployee` = `aidemployee`,`idagencies` = `aidagencies`
   WHERE `idaccount`=`aidaccount`;   
END IF;

/*taccounttype*/
IF  aidaccounttype = 0  THEN
	INSERT INTO `bd_bank`.`taccounttype`(`idaccounttype`,`accountType`,`comission`,`overdraft`,`interestRate`,`idaccount`)
	                              VALUES(aidaccounttype,aaccountType,acomission,aoverdraft,ainterestRate,aidaccount);
	SELECT 
    MAX(idaccounttype)
INTO aidaccounttype FROM
    bd_bank.taccounttype;
ELSE
   UPDATE `bd_bank`.`taccounttype`
   SET `accountType` = `aaccountType`,`comission` = `acomission`,`overdraft` = `aoverdraft`,`interestRate` = `ainterestRate`,`idaccount` = `aidaccount`
   WHERE `idaccounttype`=`aidaccounttype`;   
END IF;

/*ttransaction*/
IF  aidtransaction = 0  THEN
	INSERT INTO `bd_bank`.`ttransaction`(`idtransaction`,`balance`,`comission`,`overdraft`,`interestRate`,`idaccount`,`idclient`,`idemployee`,`idagencies`)
	                              VALUES(`aidtransaction`,`abalance`,`acomission`,`aoverdraft`,`ainterestRate`,`aidaccount`,`aidclient`,`aidemployee`,`aidagencies`);
	SELECT 
    MAX(idtransaction)
    INTO aidtransaction FROM `bd_bank`.`ttransaction`;
ELSE
   UPDATE `bd_bank`.`ttransaction`
   SET `balance` = `abalance`,`transactionDate` = now(),`comission` = `acomission`,`overdraft` = `aoverdraft`,`interestRate` = `ainterestRate`,`idaccount` = `aidaccount`,`idclient` = `aidclient`,`idemployee` = `aidemployee`,`idagencies` = `aidagencies`
   WHERE `idtransaction`=`aidtransaction`;   
END IF;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_admin
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_admin`(
in aidadmin int(11),
in aname varchar(45),
in alastName varchar(45),
in aimg varchar(45),
in aemail varchar(45),
in apassword varchar(45)

)
BEGIN

IF aidadmin = 0 THEN
INSERT INTO `bd_bank`.`tadmin`(`name`,`lastName`,`img`,`email`,`password`)
VALUES (`aname`,`alastName`,`aimg`,`aemail`,`apassword`);
SELECT 
    MAX(idadmin)
INTO aidadmin FROM
    `bd_bank`.`tadmin`;
ELSE
UPDATE `bd_bank`.`tadmin` 
SET `idadmin`=`aidadmin`,`name`=`aname`,`lastName`=`alastName`,`img`=`aimg`,`email`=`aemail`,`password`=`apassword`
WHERE `idadmin`=`aidadmin`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_agencies
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_agencies`(
in aidagencies int(11),
in aagencyNumber varchar(45),
in aname varchar(45),
in aaddress varchar(45),
in aidbank int(11),
in aidtdirectorAgencie int(11)
)
BEGIN

IF aidagencies = 0 THEN
INSERT INTO `bd_bank`.`tagencies`(`idagencies`,`agencyNumber`,`name`,`address`,`idbank`,`idtdirectorAgencie`)
VALUES (`aidagencies`,`aagencyNumber`,`aname`,`aaddress`,`aidbank`,`aidtdirectorAgencie`);
SELECT 
    MAX(idagencies)
INTO aidagencies FROM
    `bd_bank`.`tagencies`;
ELSE
UPDATE `bd_bank`.`tagencies` 
SET `idagencies`=`aidagencies`,`agencyNumber`=`aagencyNumber`,`name`=`aname`,`address`=`aaddress`,`idbank`=`aidbank`,`idtdirectorAgencie`=`aidtdirectorAgencie`
WHERE `idagencies`=`aidagencies`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_area
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_area`(
/*tarea*/
in acodearea varchar(3),
in adescription varchar(45)
)
BEGIN
/*Ajouter les inserts des tables tarea*/
DECLARE valid int;
SELECT 
    COUNT(*)
INTO valid FROM
    tarea
WHERE
    codearea = acodearea;
IF  valid=0  THEN
INSERT INTO `bd_bank`.`tarea`(codearea,description) 
VALUES(acodearea,adescription);
Else
-- Update
	UPDATE `bd_bank`.`tarea`
	SET `description`= `adescription` WHERE `codearea` = acodearea;
end if;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_client
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_client`(
in aidclient int(11),
in aclientNumber varchar(45),
in aname varchar(45),
in alastName varchar(45),
in aemail varchar(45),
in aimg varchar(45),
in aaddress varchar(45),
in acardNumber varchar(45),
in anip varchar(45),
in aidagencies int(11),
in aidemployee int(11)
)
BEGIN

IF aidclient = 0 THEN
INSERT INTO `bd_bank`.`tclient`(`idclient`,`clientNumber`,`name`,`lastName`,`email`,`img`,`address`,`cardNumber`,`nip`,`idagencies`,`idemployee`)
VALUES (`aidclient`,`aclientNumber`,`aname`,`alastName`,`aemail`,`aimg`,`aaddress`,`acardNumber`,`anip`,`aidagencies`,`aidemployee`);
SELECT 
    MAX(idclient)
INTO aidclient FROM
    `bd_bank`.`tclient`;
ELSE
UPDATE `bd_bank`.`tclient` 
SET `idclient`=`aidclient`,`clientNumber`=`aclientNumber`,`name`=`aname`,`lastName`=`alastName`,`email`=`aemail`,`img`=`aimg`,`address`=`aaddress`,`cardNumber`=`acardNumber`
WHERE `idclient`=`aidclient`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_directoragencie
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_directoragencie`(
in aidtdirectorAgencie int(11),
in aname varchar(45),
in alastName varchar(45),
in aemail varchar(45),
in aimg varchar(45),
in asalary DECIMAL(22,6)

)
BEGIN

IF aidtdirectorAgencie = 0 THEN
INSERT INTO `bd_bank`.`tdirectoragencie`(`idtdirectorAgencie`,`name`,`lastName`,`email`,`img`,`salary`)
VALUES (`aidtdirectorAgencie`,`aname`,`alastName`,`aemail`,`aimg`,`asalary`);
SELECT 
    MAX(idtdirectorAgencie)
INTO aidtdirectorAgencie FROM
    `bd_bank`.`tdirectoragencie`;

ELSE
UPDATE `bd_bank`.`tdirectoragencie` 
SET `idtdirectorAgencie`=`aidtdirectorAgencie`,`name`=`aname`,`lastName`=`alastName`,`email`=`aemail`,`img`=`aimg`,`salary`=`asalary`
WHERE `idtdirectorAgencie`=`aidtdirectorAgencie`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_directorgeneral
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_directorgeneral`(
in aiddirector int(11),
in aname varchar(45),
in alastName varchar(45),
in aimg varchar(45),
in asalary DECIMAL(22,6),
in aidbank int(11)
)
BEGIN

IF aiddirector = 0 THEN
INSERT INTO `bd_bank`.`tdirectorgeneral`(`iddirector`,`name`,`lastName`,`img`,`salary`,`idbank`)
VALUES (`aiddirector`,`aname`,`alastName`,`aimg`,`asalary`,`aidbank`);
SELECT 
    MAX(iddirector)
INTO aiddirector FROM
    `bd_bank`.`tdirectorgeneral`;

ELSE
UPDATE `bd_bank`.`tdirectorgeneral` 
SET `iddirector`=`aiddirector`,`name`=`aname`,`lastName`=`alastName`,`img`=`aimg`,`salary`=`asalary`,`idbank`=`aidbank` 
WHERE `iddirector`=`aiddirector`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_employ_area
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_employ_area`(
in aidemployee int(11),
in acodearea varchar(3)
)
BEGIN

/*Ajouter les inserts des tables temploy_area*/
DECLARE valid int;
SELECT 
    COUNT(*)
INTO valid FROM
    temploy_area
WHERE
    codearea = acodearea;

IF valid = 0 THEN
INSERT INTO `bd_bank`.`temploy_area`(`idemployee`,`codearea`)
VALUES (`aidemployee`,`acodearea`);

-- SELECT 
--    MAX(idemployee)
-- INTO aidemployee FROM `bd_bank`.`temploy_area`;
ELSE
-- Update
UPDATE `bd_bank`.`temploy_area` 
SET `idemployee`=`aidemployee`,`codearea`=`acodearea`
WHERE `idemployee`=`aidemployee`;
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_save_employee
-- -----------------------------------------------------

DELIMITER $$
USE `bd_bank`$$
CREATE DEFINER=`webclient`@`%` PROCEDURE `sp_save_employee`(
in aidemployee int(11),
in aemployeeNumber varchar(45),
in aname varchar(45),
in alastName varchar(45),
in aemail varchar(45),
in aimg varchar(45),
in ahiringDate DATE,
in aidagencies int(11)
)
BEGIN

IF aidemployee = 0 THEN
INSERT INTO `bd_bank`.`temployee`(`idemployee`,`employeeNumber`,`name`,`lastName`,`email`,`img`,`hiringDate`,`idagencies`)
VALUES (`aidemployee`,`aemployeeNumber`,`aname`,`alastName`,`aemail`,`aimg`,`ahiringDate`,`aidagencies`);
SELECT 
    MAX(idemployee)
INTO aidemployee FROM
    `bd_bank`.`temployee`;
ELSE
UPDATE `bd_bank`.`temployee` 
SET `idemployee`=`aidemployee`,`employeeNumber`=`aemployeeNumber`,`name`=`aname`,`lastName`=`alastName`,`email`=`aemail`,`img`=`aimg`,`hiringDate`=`ahiringDate`,`idagencies`=`aidagencies`
WHERE `idemployee`=`aidemployee`;
END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
